#!/usr/bin/perl

# prints coplanar circles in OFF format to stdout

use strict;
use warnings;
use File::Basename;
use Math::Trig;

if (scalar(@ARGV) == 0)
{
  print STDERR "Usage: $0 nelem radius ncircles distance\n";
  exit 0;
}

my $nelem    = defined($ARGV[0]) ? shift(@ARGV) : 40; # number of elements per circle
my $radius   = defined($ARGV[0]) ? shift(@ARGV) : 1; # radius
my $ncircles = defined($ARGV[0]) ? shift(@ARGV) : 1; # number of circles
my $distance = defined($ARGV[0]) ? shift(@ARGV) : 1; # distance between the circles

my $ntotal = $ncircles * $nelem;

# print header
print "OFF\n";
print "$ntotal $ncircles 0\n";

# print vertices
for (my $j = 0; $j < $ncircles; $j++)
{
  for (my $i = 0; $i < $nelem; $i++)
  {
    my $x = $radius * cos(2*pi*$i/$nelem);
    my $y = $radius * sin(2*pi*$i/$nelem) + $j * $distance;
    print "$x $y 0\n";
  }
}

# print polygons
for (my $j = 0; $j < $ncircles; $j++)
{
  print "$nelem";
  for (my $i = 0; $i < $nelem; $i++)
  {
    my $v = $j * $nelem + $i;
    print " $v";
  }
  print "\n";
}

print "# Generated by: ".basename($0)." $nelem $radius $ncircles $distance\n";
